repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        args: ["--fix", "--output-format=full"]
        types_or: [python, jupyter]
        language: system
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        types_or: [python, jupyter]
        language: system