ci:
  autofix_prs: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: ["--fix", "--output-format=full"]
      - id: ruff-format
        files: "(.py$)|(.*.ipynb$)"
