repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        rgs: ["--fix", "--output-format=full"]
        types_or: [python, jupyter]
      - id: ruff-format
        types_or: [python, jupyter]