name: website_projects
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pystan==2.19.1.1
  - prophet==1.0.1
  - jupyter
  - jupyterlab
  - ipywidgets
  - matplotlib
  - nb_conda_kernels
  - numpy
  - pandas
  - plotly
  - pymc3
  - bambi
  - scikit-learn
  - scipy
  - seaborn
  - shap
  - statsmodels
  - tensorflow
  - tensorflow-probability
  - sktime
  - ipykernel
  - pip:
    - pycausalimpact
